
import React, { useState } from 'react';
import { generatePPTXContent } from '../../services/geminiService';
import pptxgen from 'pptxgenjs';

interface ModalProps {
  onClose: () => void;
  onComplete: (type: 'pptx', content: string, mediaUrl?: string) => void;
}

const PPTXModal: React.FC<ModalProps> = ({ onClose, onComplete }) => {
  const [topic, setTopic] = useState('');
  const [slides, setSlides] = useState('5');
  const [isLoading, setIsLoading] = useState(false);

  const createAttractivePPTX = async (topic: string, data: any[]) => {
    const pptx = new pptxgen();
    
    // Define Master Slide / Theme
    pptx.defineSlideMaster({
      title: "CHATHDI_THEME",
      background: { color: "0D0D0D" },
      objects: [
        { rect: { x: 0, y: 0, w: "100%", h: 0.6, fill: { color: "00A3FF" } } },
        { text: { text: "ChatHDI AI Presentation", options: { x: 0.2, y: 0.1, color: "FFFFFF", fontSize: 12, bold: true } } },
        { text: { text: "Generated by ChatHDI", options: { x: 8.5, y: 5.3, color: "666666", fontSize: 10 } } }
      ]
    });

    // Title Slide
    const titleSlide = pptx.addSlide();
    titleSlide.background = { color: "0D0D0D" };
    titleSlide.addText(topic, { 
      x: 1, y: 2, w: "80%", h: 1.5, 
      fontSize: 44, bold: true, color: "00A3FF", 
      align: "center", fontFace: "Arial" 
    });
    titleSlide.addText("Produced by ChatHDI Artificial Intelligence", { 
      x: 1, y: 3.5, w: "80%", h: 0.5, 
      fontSize: 18, color: "FFFFFF", 
      align: "center" 
    });
    titleSlide.addShape(pptx.ShapeType.line, { x: 2, y: 3.4, w: 6, h: 0, line: { color: "00A3FF", width: 2 } });

    // Content Slides
    data.forEach((slideData: any) => {
      const slide = pptx.addSlide({ masterName: "CHATHDI_THEME" });
      
      // Slide Title
      slide.addText(slideData.title, { 
        x: 0.5, y: 0.8, w: "90%", h: 0.8, 
        fontSize: 28, bold: true, color: "00A3FF",
        valign: "middle"
      });

      // Slide Content (Bullets)
      const bullets = slideData.content.map((point: string) => ({ text: point, options: { bullet: true, color: "FFFFFF", fontSize: 16, margin: 5 } }));
      slide.addText(bullets, { 
        x: 0.5, y: 1.8, w: "90%", h: 3, 
        fontSize: 16, color: "FFFFFF",
        valign: "top"
      });
      
      // Decorative elements
      slide.addShape(pptx.ShapeType.rect, { x: 0.2, y: 0.8, w: 0.1, h: 0.8, fill: { color: "00A3FF" } });
    });

    // Final Slide
    const endSlide = pptx.addSlide();
    endSlide.background = { color: "00A3FF" };
    endSlide.addText("Terima Kasih", { 
      x: 0, y: 2.2, w: "100%", h: 1, 
      fontSize: 50, bold: true, color: "FFFFFF", align: "center" 
    });
    endSlide.addText("Presentasi ini dibuat secara otomatis oleh ChatHDI", { 
      x: 0, y: 3.2, w: "100%", h: 0.5, 
      fontSize: 14, color: "FFFFFF", align: "center" 
    });

    const fileName = `ChatHDI_${topic.replace(/\s+/g, '_')}.pptx`;
    await pptx.writeFile({ fileName });
    return fileName;
  };

  const handleGenerate = async () => {
    if (!topic) return;
    setIsLoading(true);
    try {
      const content = await generatePPTXContent(topic, parseInt(slides));
      if (content && content.length > 0) {
        const fileName = await createAttractivePPTX(topic, content);
        onComplete('pptx', `Selesai membuat presentasi profesional untuk: ${topic}. File "${fileName}" telah diunduh secara otomatis.`);
        onClose();
      }
    } catch (error) {
      console.error(error);
      alert("Gagal membuat presentasi. Silakan periksa koneksi dan API Key Anda.");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/80 backdrop-blur-sm p-4">
      <div className="bg-[#1e1e1e] w-full max-w-lg rounded-2xl border border-white/10 shadow-2xl overflow-hidden">
        <div className="p-6 border-b border-white/10 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-orange-500 flex items-center justify-center">
               <svg className="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg>
            </div>
            <div>
              <h2 className="text-xl font-bold">Buat Presentasi</h2>
              <p className="text-xs text-gray-500">Generate PPTX dengan AI</p>
            </div>
          </div>
          <button onClick={onClose} className="text-gray-500 hover:text-white transition-colors">
            <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" /></svg>
          </button>
        </div>

        <div className="p-6 space-y-6">
          <div className="bg-orange-500/10 border border-orange-500/20 p-3 rounded-xl text-xs text-orange-300">
            ChatHDI akan merancang struktur slide yang menarik dan mengunduh file .pptx siap pakai ke perangkat Anda.
          </div>

          <div className="space-y-2">
            <label className="text-sm font-medium text-gray-300">Topik Presentasi</label>
            <textarea 
              value={topic}
              onChange={(e) => setTopic(e.target.value)}
              placeholder="Contoh: Strategi Implementasi Hidrogen di Sektor Transportasi"
              className="w-full bg-[#121212] border border-white/10 rounded-xl p-3 h-24 focus:outline-none focus:ring-1 focus:ring-orange-500/50 resize-none text-sm"
            />
          </div>

          <div className="space-y-2">
            <label className="text-sm font-medium text-gray-300">Jumlah Slide</label>
            <select 
              value={slides}
              onChange={(e) => setSlides(e.target.value)}
              className="w-full bg-[#121212] border border-white/10 rounded-xl p-3 text-sm focus:outline-none focus:ring-1 focus:ring-orange-500/50"
            >
              <option value="5">5 Slide Utama</option>
              <option value="10">10 Slide Mendalam</option>
              <option value="15">15 Slide Komprehensif</option>
            </select>
          </div>
        </div>

        <div className="p-6 border-t border-white/10 flex gap-3">
          <button onClick={onClose} className="flex-1 py-3 text-sm font-medium hover:bg-white/5 rounded-xl transition-colors">
            Batal
          </button>
          <button 
            onClick={handleGenerate}
            disabled={isLoading || !topic}
            className={`flex-1 py-3 rounded-xl bg-orange-600 text-white text-sm font-medium transition-all flex items-center justify-center gap-2 ${isLoading || !topic ? 'opacity-50 cursor-not-allowed' : 'hover:bg-orange-700 shadow-lg shadow-orange-900/20'}`}
          >
            {isLoading ? (
              <svg className="animate-spin h-5 w-5 text-white" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path></svg>
            ) : (
              <><svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 16v1a2 2 0 002 2h12a2 2 0 002-2v-1m-4-4l-4 4m0 0l-4-4m4 4V4" /></svg> Generate PPTX</>
            )}
          </button>
        </div>
      </div>
    </div>
  );
};

export default PPTXModal;
